medik8s/self-node-remediation

api/v1alpha1/selfnoderemediationconfig_webhook.go, api/v1alpha1/selfnoderemediationconfig_webhook_test.go
Fixed the selfNodeRemediationConfig webhook validation to contain all fields with wrong values (instead of only the first one that was found wrong)
=> Fix webhook validation error message

api/v1alpha1/selfnoderemediationconfig_types.go, api/v1alpha1/selfnoderemediationtemplate_types.go, main.go
For UI it's to use existing templates instead of creating them itself. So we provide templates for both remediation strategies now. The decision which one is the default is up to NHC then, by using the relevant template name in the NHC default config.
=> Create templates for both remediation strategies

.github/workflows/post-submit.yaml, Makefile
- build and push bundle (will be used by NHC  CI)
- for merges to main use version 0.0.1 (will be used by NHC  CI)
- for tags use version from tag with stripped "v" prefix
=> Update image build and push in CI

controllers/controller_test.go, controllers/selfnoderemediation_controller.go, install/self-node-remediation-deamonset.yaml
- Adding a  `No Execute` taint in order to make sure after reboot the node is not running any workload - this is important so we can move this workload elsewhere even if the node does not have connectivity to the control plain.
- Once a node is healthy the taint is removed.
=> Add/Remove No Execute Taint

.github/workflows/post-submit.yaml, .github/workflows/pre-submit.yaml, Makefile
- Updating GitHub Action versions (similar to [NMO PR](https://github.com/medik8s/node-maintenance-operator/pull/24) and [NHC PR](https://github.com/medik8s/node-healthcheck-operator/pull/98)):
- [actions/checkout](https://github.com/actions/checkout/tree/main) and  [actions/setup-go](https://github.com/actions/setup-go/tree/main) versions from 2 to 3.
- [docker/login-action](https://github.com/docker/login-action) from version 1 to 2.
- Using `IMAGE_TAG` instead of `VERSION`.
- Adding _bundle_ and _catalog_ `build` and `push` and two new targets (`container-build` & `container-push`) for CI in Makefile.
=> Updating Github action versions + post PR functionality

Makefile
The Github action of #13 post PR has [failed](https://github.com/medik8s/self-node-remediation/runs/6966313937?check_suite_focus=true), due to missing target of _opm_ which is used for building a catalog image.
=> Add opm target for building catalog image

api/v1alpha1/webhook_suite_test.go, controllers/controller_test.go, controllers/selfnoderemediation_controller.go, controllers/suite_test.go, e2e/self_node_remediation_test.go, pkg/certificates/suite_test.go, pkg/peerhealth/suite_test.go
In manual tests and NHC CI the NoExecute taint isn't removed after remediation.
For debugging and fixing the issue this PR evolved over time and mainly contains these changes:
- add e2e test for the taint (didn't reproduce the issue)
- add taint after adding finalizer (didn't fix the issue)
- wait for removal of Unschedulable Taint after setting Unschedulable to false: this fixed the issue! It was a race between node-lifecycle-controller and us with removing taints
more changes:
- added logging
- fix running unit test when they break (prevent metrics port conflicts)
- use existing DeleteTaint func
- add TimeAdded to taint
=> Fix taint removal

Dockerfile
Updating the current base image, [ubi](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index#con_understanding-the-ubi-micro-images_assembly_types-of-container-images), to a newer and even smaller image , [ubi-micro](https://www.redhat.com/en/blog/introduction-ubi-micro), for building the operator (in Dockerfile).
Using smaller image minimizes the attack surface of container images, and is suitable for minimal applications.
See similar PR in NMO - https://github.com/medik8s/node-maintenance-operator/pull/37
=> Use ubi-micro as base image in Dockerfile

bundle.Dockerfile, bundle/manifests/self-node-remediation.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manifests/bases/self-node-remediation.clusterserviceversion.yaml, controllers/controller_test.go, controllers/selfnoderemediation_controller.go, e2e/self_node_remediation_test.go
- Removing the no Execute taint only when SNR is targeted for deletion, in order to prevent a situation where the taint is removed but the node isn't ready for workload yet.
=> Remove taint and finalizer only when SNR is targeted to delete by NHC

Dockerfile
Reverts medik8s/self-node-remediation#34
It breaks watchoog and soft reboot because of missing `/usr/bin/nsenter`
=> Revert "Use ubi-micro as base image in Dockerfile"

.github/workflows/post-submit.yaml
Add build step for building and pushing versioned NHC + SNR + index images.
Similar for NHC: https://github.com/medik8s/node-healthcheck-operator/pull/107
[ECOPROJECT-877](https://issues.redhat.com//browse/ECOPROJECT-877)
=> Build index image with latest NHC + SNR for merged PRs to main

bundle/tests/scorecard/config.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml
SNR's scorecard test, `olm-status-descriptors-test `,  [has failed before](https://github.com/operator-framework/operator-sdk/issues/5548) and in order to use the [new fix](https://github.com/operator-framework/operator-sdk/pull/5948) we need to update the scorecard test version to the latest version -[`v1.25.2`](https://github.com/operator-framework/operator-sdk/releases).
[ECOPROJECT-1070](https://issues.redhat.com//browse/ECOPROJECT-1070)
=> Update scorecard version to fix olm-status-descriptors-test bug

Makefile, bundle.Dockerfile, bundle/manifests/self-node-remediation.clusterserviceversion.yaml, bundle/metadata/annotations.yaml
As part of [ECOPROJECT-926](https://issues.redhat.com//browse/ECOPROJECT-926)
- aligned versions to the top of make file
- operator sdk updated from 1.19 to 1.25.3
- kustomize updated from 4.5.4 to 4.5.7 & and modified not to cache the old version
- opm updated from 1.25 to 1.26.2 & and modified not to cache the old version
=> Update build tool versions in SNR 0.5

main.go, pkg/apicheck/check.go, pkg/peers/response.go
[ECOPROJECT-1028](https://issues.redhat.com//browse/ECOPROJECT-1028) bug fix.
Adding a grace time before deciding that a worker peer is unresponsive. 
This way node will not assume it's isolated due to to short network/communication issue.
I've managed to recreate the bug and test the fix on 4.12 OCP
=> Bug Fix ECOPROJECT-1028

e2e/self_node_remediation_test.go, e2e/utils/pod.go
Checking for a flag in order to skip some log validations which are failing on ocp 4.12 ci
=> Enabling e2e  tests for 4.12 ocp

pkg/apicheck/check.go, pkg/controlplane/manager.go, pkg/peers/response.go
Fixing a use-case when control-plane was making an unnecessary reboot due to the use case missing in the `switch`.
Bug fixes for [ECOPROJECT-1097](https://issues.redhat.com//browse/ECOPROJECT-1097) , [ECOPROJECT-1100](https://issues.redhat.com//browse/ECOPROJECT-1100)
=> Fixing wrong scenario of control-plane reboot

controllers/selfnoderemediation_controller_test.go, controllers/suite_test.go, pkg/reboot/rebooter.go, pkg/reboot/rebooter_test.go, pkg/reboot/suite_test.go, pkg/utils/annotations.go, pkg/watchdog/fake.go, pkg/watchdog/synchronized.go
Fix for [ECOPROJECT-483](https://issues.redhat.com//browse/ECOPROJECT-483) .
Previously the use case where WD failed to start was ignored - which might have ultimately caused a failure to fence/remediate a failed node later on.
Now, in case software reboot **isn't enabled** SNR will fail to initialize.
In case watchdog failed to start and software reboot **is enabled** we will failover to software reboot.
=> Watchdog init logic

e2e/self_node_remediation_test.go, e2e/utils/pod.go
I've noted that sometimes tests fails due to timeouts waiting for pods to start / waiting for pods to be available.
I see different behavior on my own cluster (rarely fails) and also during different times of day - I assume it has to do with resource usage.
Extending the test times which are prone to cause e2e tests fail in order to improve tests stability.
=> Extend some test wait times

Makefile, api/v1alpha1/webhook_suite_test.go, go.mod, pkg/peerhealth/client_server_test.go, pkg/peerhealth/suite_test.go
Investigate flaky unit test.
```
Failure [20.009 seconds]
[AfterSuite] AfterSuite 
/go/src/github.com/medik8s/self-node-remediation/pkg/peerhealth/suite_test.go:95
Unexpected error:
<errors.aggregate | len:1, cap:1>: [
<*errors.errorString | 0xc00018d180>{
s: "timeout waiting for process kube-apiserver to stop",
},
]
timeout waiting for process kube-apiserver to stop
occurred
/go/src/github.com/medik8s/self-node-remediation/pkg/peerhealth/suite_test.go:99
```
Happens sometimes in OpenshiftCI, e.g. https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/medik8s_self-node-remediation/49/pull-ci-medik8s-self-node-remediation-main-4.13-test/1612741423029817344
Happens more often in github workflow of NHC, e.g. https://github.com/medik8s/node-healthcheck-operator/actions/runs/38854932 …
=> Fix flaky unit test

Makefile
Download the protoc binary first, because
the golang image misses the needed "unzip" tool
This blocks NHC CI
Reproducer without this PR: delete ./bin, run `make check`
=> Add "protoc" as dependency for "check" target

bundle/manifests/self-node-remediation.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/selfnoderemediation_controller.go
This fixes errors like the one reported in the logs.
```
E0203 12:05:27.009380 2699 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.3/tools/cache/reflector.go:167: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:self-node-remediation:self-node-remediation-controller-manager" cannot list resource "namespaces" in API group "" at the cluster scope 
E0203 13:00:27.442104 2699 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.3/tools/cache/reflector.go:167: Failed to watch *v1.Namespace: unknown (get namespaces) 
```
Relevant Jira ticket - [ECOPROJECT-1183](https://issues.redhat.com//browse/ECOPROJECT-1183)
=> Add RBAC permissions for namespaces.

controllers/selfnoderemediation_controller.go, controllers/suite_test.go, main.go, pkg/apicheck/check.go, pkg/reboot/calculator.go, pkg/reboot/rebooter.go, pkg/reboot/rebooter_test.go
[ECOPROJECT-1197](https://issues.redhat.com//browse/ECOPROJECT-1197)
ATM when we calculate SNR timeout we are sampling all the worker nodes in batches of 10% of the nodes in each batch.
Therefore we calculate the timeout assuming 10 batches.
In case a cluster has fewer than 10 worker nodes this calculation can be optimized.
=> Reduce timeout for compact (or otherwise small) clusters

pkg/apicheck/check.go, pkg/reboot/calculator.go
Followup PR for [this](https://github.com/medik8s/self-node-remediation/pull/91#pullrequestreview-1317265132) comment.
increase the minimum number of worker nodes in each batch from 1 to 3 in order to reduce timeout in clusters with low number of worker nodes.
=> increase the minimum batch size

api/v1alpha1/selfnoderemediation_types.go, bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml, bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml, config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediations.yaml, config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml, controllers/selfnoderemediation_controller.go, controllers/selfnoderemediation_controller_test.go
This PR is adding a new remediation strategy based on https://github.com/kubernetes/enhancements/pull/1116
In k8s 1.26, https://github.com/kubernetes/enhancements/pull/1116 is a Beta feature. This feature will be graduated to GA in k8s 1.27.
This PR is implemented based on the discussion in https://github.com/medik8s/self-node-remediation/issues/17.
The following is the new remediation strategy for the out-of-service taint:
1. When detecting node failure by NHC, SNR sets NoExecute taint on the failed Node
2. The failed node is rebooted by watchdog
3. SNR waits for a fixed time to complete rebooting the failed node
4. SNR sets the out-of-service taint
=> This taint expects that the node is in shutdown or power off state (not in the middle of restarting) according to [the …
=> Add out of service taint remediation

PROJECT, api/v1alpha1/selfnoderemediationtemplate_webhook.go, api/v1alpha1/selfnoderemediationtemplate_webhook_test.go, api/v1alpha1/webhook_suite_test.go, bundle/manifests/self-node-remediation.clusterserviceversion.yaml, config/webhook/manifests.yaml, main.go
Verifying out of service taint is supported before allowing the user to set it.
=> Validate k8s version for out-of-service-taint remediation strategy

controllers/selfnoderemediation_controller.go
Due to multiple snr agents patching the status there is a risk of corrupting the status data.
Switching into update in order to resolve that.
more context [here](https://redhat-internal.slack.com/archives/C03ACTRQWE9/p1680102241235559)
=> update status instead of patch

api/v1alpha1/selfnoderemediation_webhook.go, bundle/manifests/self-node-remediation.clusterserviceversion.yaml, config/webhook/manifests.yaml
When the operator is running on the unhealthy node, webhook calls fail, and NHC can't create CRs without this change.
The webhook was introduced for [ECOPROJECT-1232](https://issues.redhat.com//browse/ECOPROJECT-1232) in #108.
`2023-04-05T07:14:23.675898862Z	ERROR	controllers.NodeHealthCheck	failed to start remediation	{"NodeHealthCheck name": "test-nhc", "error": "failed to create remediation CR: Internal error occurred: failed calling webhook \"vselfnoderemediation.kb.io\": failed to call webhook: Post \"[https://self-node-remediation-controller-manager-service.k8s-test.svc:443/validate-self-node-remediation-medik8s-io-v1alpha1-selfnoderemediation?timeout=10s\](https://self-node-remediation-controller-manager-service.k8s-test.svc/validate-self-node-remediation-medik8s-io-v1alpha1-selfnod …
=> Allow creating remediation CRs when webhook is down

controllers/selfnoderemediation_controller.go
As a follow up on [this](https://github.com/medik8s/self-node-remediation/pull/102#discussion_r1156211127) comment, setting minimum requeue time in case update failed instead of keeping the original requeue time.
=> setting minimum requeue time in case update failed

controllers/selfnoderemediation_controller.go
This PR is meant to solve [ECOPROJECT-1243](https://issues.redhat.com//browse/ECOPROJECT-1243)
more context at slack conversation [here](https://redhat-internal.slack.com/archives/C03M5GKJNBA/p1681892288662789)
=> Ignore NHC timeout annotation on deletion of snr

api/v1alpha1/selfnoderemediation_types.go, bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml, bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml, config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediations.yaml, config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
- Removing the mention of "NodeDeletion" Strategy
- As part of [ECOPROJECT-1237](https://issues.redhat.com//browse/ECOPROJECT-1237) updating the description so it'll be clearer to the user as to why `OutOfServiceTaint` strategy can't be selected.
Note: This isn't planned for SNR 0.6.0
=> Bugfix 1237 - update Remediation strategy description

.github/workflows/post-submit.yaml, .github/workflows/pre-submit.yaml, Makefile
Similar to the rest of Medik8s operators we add an automation for the creation of Github Release upon Git tag creation.
[ECOPROJECT-1128](https://issues.redhat.com//browse/ECOPROJECT-1128)
1. Add Github Action step for building the draft.
2. Use container-build-community target for CI so _quay.io/medik8s_ will store SNR's community version for K8s.
=> Automate GitHub Release Draft

.github/workflows/post-submit.yaml, .github/workflows/pre-submit.yaml, Makefile
Follow up PR to #117 which will overcome the problem with **CGO_ENABLED=0** in controller-gen binary, when we update [hosted runner Ubuntu image for github-actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners) - `ubuntu-20.04` -> `ubuntu-22.04`.
=> Use Ubuntu 22 as Hosted Runner in Github CI

.ci-operator.yaml, ci-operator.yaml
Fix for [PR](https://github.com/medik8s/self-node-remediation/pull/127)
- remove redundant ci-operator.yaml and update .ci-operator.yaml with correct golang version
=> Fix prev PR meant to use golang version from SNR repo in CI

api/v1alpha1/selfnoderemediation_types.go
Removed '+patchMergeKey' and '+patchStrategy' markers.
These are for guiding strategic merge, which is not supported on CRDs.
According to https://github.com/kubernetes-sigs/gateway-api/issues/342 the markers +patchMergeKey' and '+patchStrategy' don't work on CRDs.
I've tested this by running `make generate` and `make manifests` and the resulting yaml CRD didn't change.
The desired effect in config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediations.yaml
```
type: array
x-kubernetes-list-map-keys:
- type
x-kubernetes-list-type: map
```
is from '+listType' and '+listMapKey' as already applied.
=> Removed '+patchMergeKey' and '+patchStrategy' markers.

Makefile
Add TEST_OPS variable to permit passing convenient flags while
adding or updating tests/features
e.g.
* -ginkgo.v[v]
* -ginkgo.focus <test name>
Signed-off-by: Carlo Lobrano <c.lobrano@gmail.com>
=> Permit to pass further options to Makefile test targets

controllers/selfnoderemediation_controller.go
This PR is adding the following messages:
1. Add a message about deleting out-of-service taint 
2. Add a message about waiting for terminating pod when checking resource deletion
3. Add a message about waiting for deleting volumeAttachment when checking resource deletion
[ECOPROJECT-1241](https://issues.redhat.com/browse/ECOPROJECT-1241)
=> Add log messages to trace OutOfServiceTaint remediation

pkg/certificates/credentials.go, pkg/controlplane/manager.go
Currently, the default MinVersion value for TLS configuration is used,
which is TLS1.0 and considered insecure.
Explicitly set the MinVersion to a secure version of TLS.
closes: https://issues.redhat.com/browse/ECOPROJECT-1419
Signed-off-by: Carlo Lobrano <c.lobrano@gmail.com>
=> Explicitly set MinVersion of TLS

controllers/selfnoderemediation_controller.go, controllers/selfnoderemediation_controller_test.go
[ECOPROJECT-1492](https://issues.redhat.com//browse/ECOPROJECT-1492)
Incorrect Status Conditions in case non existed node in Remediation CR .
When SNR is created for a non existing node Processing condition is True and Reason is RemediationStarted. 
Expected values are processing = false, succeeded = false with reason NodeNotFound.
=> Stop remediation when node not found

api/v1alpha1/selfnoderemediationconfig_types.go, bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml, config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml, controllers/selfnoderemediationconfig_controller.go, controllers/selfnoderemediationconfig_controller_test.go, install/self-node-remediation-deamonset.yaml, main.go
[ECOPROJECT-1581](https://issues.redhat.com//browse/ECOPROJECT-1581)
Currently the hostPort: 30001 is fixed by the operator and is no possible to change, making it impossible for pods to deploy if that port is already in use.
This PR makes the port configurable.
=> configure host port

api/v1alpha1/selfnoderemediationconfig_types.go, controllers/selfnoderemediationconfig_controller.go, main.go
[ECOPROJECT-1630](https://issues.redhat.com//browse/ECOPROJECT-1630)
safeTimeToAssumeNodeRebootedSeconds doesn't impact actual time of node returning to health.
=> config value of safe time to reboot was calculated wrongly

controllers/selfnoderemediation_controller.go, controllers/selfnoderemediationconfig_controller.go, controllers/tests/config/selfnoderemediationconfig_controller_test.go, controllers/tests/config/suite_test.go, controllers/tests/controller/selfnoderemediation_controller_test.go, controllers/tests/controller/suite_test.go, controllers/tests/shared/shared.go, main.go, pkg/peerhealth/suite_test.go, pkg/reboot/calculator.go, pkg/reboot/rebooter.go, pkg/reboot/rebooter_test.go, pkg/watchdog/fake.go
[ECOPROJECT-1261](https://issues.redhat.com//browse/ECOPROJECT-1261)
At the moment, upon a remediation detected by SNR all DaemSets (i.e all SNR agent - each on every node) will perform APIServer calls as part of SNR remediation process.
In large clusters that can cause an overload on the APIServer.
We need to consider a solution to reduce the amount of APIServer call in order to minimize that risk.
=> Handle large cluster load

pkg/peerhealth/client.go
Currently if peerhealth.NewClient is called with no
credentials.TransportCredentials it uses a DialOption which disables
transport security for this ClientConn.
Considering also the in the current code base it is not possible to
reach this point without valid credentials, this commit removes the
usage of such DialOption and returns with error instead for security
reasons.
=> Do not create PeerHealth new client without credentials

Dockerfile, hack/build.sh, main.go, version/version.go
Adding info about go version (and additional info) in logs.
[ECOPROJECT-1743](https://issues.redhat.com//browse/ECOPROJECT-1743)
=> print versions

controllers/selfnoderemediation_controller.go, controllers/tests/config/suite_test.go, controllers/tests/controller/selfnoderemediation_controller_test.go, controllers/tests/controller/suite_test.go, controllers/tests/shared/shared.go, e2e/self_node_remediation_test.go, go.mod, go.sum, vendor/github.com/medik8s/common/pkg/resources/resources.go, vendor/modules.txt
[ECOPROJECT-1748](https://issues.redhat.com//browse/ECOPROJECT-1748)
VA should not be deleted by SNR. kube-control-manager (KCM) detects the pod deletion and automatically detaches the VAs which are not connected to any pod, forcefully deleting the VA has the risk of interfering with the process of detaching the VAs.
=> remove VA deletion

api/v1alpha1/selfnoderemediation_types.go, api/v1alpha1/selfnoderemediationtemplate_types.go, go.mod, go.sum, vendor/github.com/medik8s/common/pkg/labels/labels.go, vendor/modules.txt
[ECOPROJECT-1759](https://issues.redhat.com//browse/ECOPROJECT-1759)
ATM The UI is looking for SNR Template with the default remediation strategy completely hard coded (i.e hard coded for ResourceDeletion).
In order to make the UI more robust and prevent unnecessary changes in the UI when the default Strategy is changed, we'd put a label on the Template with the default strategy instead.
=> adding label on default template

api/v1alpha1/selfnoderemediation_types.go, api/v1alpha1/selfnoderemediationtemplate_types.go, bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml, bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml, config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediations.yaml, config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml, controllers/selfnoderemediation_controller.go, controllers/tests/controller/selfnoderemediation_controller_test.go, main.go, pkg/utils/taints.go, pkg/utils/taints_test.go
[ECOPROJECT-1752](https://issues.redhat.com//browse/ECOPROJECT-1752)
At the moment the default remediation Strategy is `ResourceDeletion`, for newer clusters (ocp 4.14+) it's recommended to use the newer implementation of the Out of Service taint which is used in the `OutOfService` strategy.
In order to achieve this we plan to create a new default strategy `Automatic` which will decide the remediation strategy SNR will use at runtime depending on the cluster.
This change also meant for a better integration of other future strategies
=> Automatic remediation strategy

controllers/selfnoderemediation_controller.go, controllers/tests/controller/selfnoderemediation_controller_test.go, install/self-node-remediation-deamonset.yaml
[ECOPROJECT-1747](https://issues.redhat.com//browse/ECOPROJECT-1747)
Adding a node selector which will allow preventing SNR daemonset to run on a specific node.
This functionality is required for use cases where we would like to disable SNR (for example Node maintenance).
=> adding node selector to snr daemonset

controllers/selfnoderemediation_controller.go, controllers/tests/controller/selfnoderemediation_controller_test.go, controllers/tests/controller/suite_test.go, pkg/peerhealth/server.go
[ECOPROJECT-1772](https://issues.redhat.com//browse/ECOPROJECT-1772)
SNR Misinterprets CR Association when template configures in openshift-machine-api ns, leading to Incorrect peer check in case of API issues.
When a SNR template is configured in the openshift-machine-api for use with NHC, an issue arises. SNR incorrectly assumes that CRs  are generated by MHC and wrongly identifies the CR name as the Machine name. 
However, the CR name corresponds to the Node name.This misinterpretation becomes problematic during peer checks,in case of API issues. 
SNR searches for CRs using the incorrect Machine name instead of the Node name. 
Consequently, it consistently returns a "you're healthy" status, as it fails to locate the expected CR associated with the Node name.
=> SNR wrongly identify the remediation created by MHC (instead of NHC)

Makefile, bundle/manifests/self-node-remediation.clusterserviceversion.yaml, config/manifests/bases/self-node-remediation.clusterserviceversion.yaml
[ECOPROJECT-1767](https://issues.redhat.com//browse/ECOPROJECT-1767)
We need to update our CSVs with the following required metadata:
1. "replace" field:
while we use "skipRange" for defining from which versions we can update to the version of the CSV, we also need to add the "replace" field. It should point to the last released version, and ensures that the old version isn't deleted from the index, so customers can continue to use their tested and approved version.
https://docs.engineering.redhat.com/display/CFC/Best_Practices#Best_Practices-SkipRange
=> add 'replaces' to csv

controllers/selfnoderemediation_controller.go, controllers/tests/controller/selfnoderemediation_controller_test.go
[ECOPROJECT-1815](https://issues.redhat.com//browse/ECOPROJECT-1815)
Improve naming for condition.
=> improve condition name

e2e/self_node_remediation_test.go
This PR is adding a new e2e tests for OutOfServiceTaint remediation strategy based on https://github.com/kubernetes/enhancements/pull/1116.
And https://github.com/openshift/release/pull/47048 depends on this pr.
=> Add e2e tests for OutOfServiceTaint remediation

Makefile, controllers/selfnoderemediation_controller.go, controllers/tests/controller/selfnoderemediation_controller_test.go, go.mod, go.sum, vendor/github.com/medik8s/common/pkg/events/events.go, vendor/github.com/medik8s/common/pkg/labels/labels.go, vendor/modules.txt
[ECOPROJECT-1826](https://issues.redhat.com//browse/ECOPROJECT-1826), [ECOPROJECT-1827](https://issues.redhat.com//browse/ECOPROJECT-1827), [ECOPROJECT-1829](https://issues.redhat.com//browse/ECOPROJECT-1829)
Fixing some minor bugs improving SNR logs and events
=> Logs and events fixes

controllers/selfnoderemediationconfig_controller.go
[ECOPROJECT-1828](https://issues.redhat.com//browse/ECOPROJECT-1828)
Some log errors show on operator start due to a conflict of updating the ds
=> Clean operator start errors due to update conflict

controllers/tests/config/selfnoderemediationconfig_controller_test.go, controllers/tests/controller/selfnoderemediation_controller_test.go, pkg/peerhealth/client_server_test.go
Fixing flaky UT, and removing VA logic since SNR does not delete VA's anymore
=> fix flaky UT

controllers/selfnoderemediationconfig_controller.go
[ECOPROJECT-1828](https://issues.redhat.com//browse/ECOPROJECT-1828) 
fixing error code missing because of wrong error conversion
=> fixing error code missing because of wrong error conversion

controllers/selfnoderemediation_controller.go, controllers/tests/config/selfnoderemediationconfig_controller_test.go
[ECOPROJECT-1862](https://issues.redhat.com//browse/ECOPROJECT-1862) 
- Considering a use case where the finalizer is placed by the agent and than we loose connectivity after reboot, missing this log message.
- Also fixing a flaky UT in config
=> Updating "Automatic" log message

controllers/selfnoderemediation_controller.go
[ECOPROJECT-1864](https://issues.redhat.com//browse/ECOPROJECT-1864)
fixing a regression where SNR doesn't record the last error in case node isn't found.
=> Last error not recorded

controllers/selfnoderemediation_controller.go, controllers/tests/controller/selfnoderemediation_controller_test.go, go.mod, go.sum, vendor/github.com/medik8s/common/pkg/events/events.go, vendor/modules.txt
[ECOPROJECT-1836](https://issues.redhat.com//browse/ECOPROJECT-1836)
- not omitting remediation started event for not found nodes
- using node not found event from common
- adding indication of whether the message was omitted by the agent or manager
=> Events refactoring

bundle/manifests/self-node-remediation.clusterserviceversion.yaml, config/default/kustomization.yaml, config/default/manager_auth_proxy_patch.yaml
It enables kube-rbac-proxy container so we could reach metrics.
- Uncomment `manager_auth_proxy_patch.yaml`
- Regenerate bundle manifests
Fixes #196, as I hope :)
[ECOPROJECT-1949](https://issues.redhat.com//browse/ECOPROJECT-1949)
=> Enable kube-rbac-proxy to be able to reach metrics

api/v1alpha1/selfnoderemediationconfig_types.go, api/v1alpha1/selfnoderemediationconfig_webhook.go, api/v1alpha1/selfnoderemediationconfig_webhook_test.go, pkg/utils/annotations.go
SNR has a maximum of one agent created by it's daemonset on each node.
All of these agents are using a single configuration, therefore having more than one configuration may cause an unexpected behavior.
ATM there is no limitation on creating multiple SNR configuration, the purpose of this PR is to make sure there will be no more than one configuration for SNR.
- Added a unique  annotation on the default configuration.
- Added a validation on creation of a configuration that this annotation exist, otherwise the create is rejected.
[ECOPROJECT-1997](https://issues.redhat.com//browse/ECOPROJECT-1997)
If there is not a correspondent issue yet, you might want to open a new one yourself, describing the problem you observed.
-->
=> Verify there is no more than one configuration

PROJECT, api/v1alpha1/selfnoderemediationtemplate_webhook.go, bundle/manifests/self-node-remediation.clusterserviceversion.yaml, config/webhook/manifests.yaml, controllers/selfnoderemediation_controller.go, controllers/tests/controller/selfnoderemediation_controller_test.go, go.mod, go.sum, vendor/github.com/medik8s/common/pkg/annotations/annotations.go, vendor/github.com/medik8s/common/pkg/events/events.go, vendor/modules.txt
This PR will enable the user to select several SNR Templates (of the same kind) when using NHC escalating remediation.
This feature is dependent on the changes in NHC as well (which is available starting from NHC 0.8.0).
- Automatically add the `MultipleTemplatesSupportedAnnotation` that enables this feature via "Defaulting" (Mutating) webhook.
- Support that Node's name might come from `NodeNameAnnotation` instead than from remediation's name (when the feature is enabled).
- Updated Common package to the version shipping the new annotations needed by this feature.
- Test coverage for both configurations (supported and unsupported multiple same kind remediation).
https://issues.redhat.com/browse/ECOPROJECT-1930
=> Support Multiple Same Kind Remediation

.github/workflows/post-submit.yaml, .github/workflows/release.yml
Currently, the GitHub Action workflow is only able to create a RH/OKD bundle, while SNR is also supported in K8S community.
Moreover, the need of inputs like `previous version` does not allow to keep using the automatic CI for the release.
Create a manual workflow to provide the necessary inputs to the shared 
GitHub Action to:                                                      
- build and push versioned images to quay registry                     
- create the OKD release branch, ready for the PR                      
- create the K8S release branch, ready for the PR                     
It contributes to solving
[ECOPROJECT-1579](https://issues.redhat.com/browse/ECOPROJECT-1579)
Tested locally via nektos/act.
=> Automate community bundle via GitHub Actions

e2e/self_node_remediation_test.go
Flaky e2e
Increase timeout on deleteAndWait in e2e.
This used for deleting SNR CRs, which only works when remediation is done, which can take longer than 2 min.
=> Increase timeout on deleteAndWait in e2e

Makefile, e2e/self_node_remediation_test.go
This PR introduces some required and nice-to-have improvements to E2E tests
- Replace deprecated ginko progress with increased verbosity
- Improve logging
- Set labels for unrestricted PSA on namespace
=> e2e test improvement

pkg/reboot/calculator.go, pkg/reboot/calculator_test.go
calculator unit test times out sometimes because config wasn't set yet
- fix lock when reading only (will probably have no significant effect though)
- increase unit test timeout to wait for config being set in calculator
=> Fix calculator lock and unit test

pkg/reboot/calculator.go
Slightly wrong log message:
`2024-07-05T06:32:29.280007573Z	INFO	rebootDurationCalculator	No SafeTimeToAssumeNodeRebootedSeconds specified, using calculated minimum safe reboot time	{"calculated minimum time in seconds": "2m0s"}`
Should be `120` instead of `2m0s`
Take `Seconds()` from duration in log
Fixes [ECOPROJECT-2025](https://issues.redhat.com//browse/ECOPROJECT-2025)
=> Fix log message

controllers/selfnoderemediation_controller.go
Currently when SNR is disabled because of missing configuration, the
condition's reason is "SNRDisabledConfigurationNotFound", however
- we already know it's about SNR
- we know, from the type, that is about "Disable"
https://issues.redhat.com/browse/ECOPROJECT-2026
=> Simplify naming for condition

controllers/tests/config/selfnoderemediationconfig_controller_test.go
This variable was used in an[ early stage](https://github.com/medik8s/self-node-remediation/pull/204/commits/c220fcfe77ec17d7811a1e1085124f15ec14ee0b#diff-91365162a1d1121a55c65ac4980e04d17aa1dead56aaa10a688b2032de96a831R258) of #204, the final merged version of that  PR didn't use this variable making it redundant, so it should be removed.
removing unused variable
Technical debt
=> Remove unused variable `isSkipCleanup`

main.go, pkg/utils/taints.go
During release testing of SNR we've noticed one case were SNR template with Out Of Service taint strategy could not be created.
The reason for that was that because when SNR was initialized,  it failed to fetch the k8s version therefore SNR couldn't verify support for Out Of Service taint.
We couldn't reproduce this, but we suspect this occurred due to a temporary network issue. 
In order to minimize similar occurrences in the future a retry mechanism is added.
Adding links to our slack discussion on that subject. [[1]](https://redhat-internal.slack.com/archives/C03M5GKJNBA/p1720704425398739) [[2]](https://redhat-internal.slack.com/archives/C03M5GKJNBA/p1720809806541209)
In case Out Of Service flags can't be set at the first attempt (due to failing getting the k8s version or any other …
=> Retry setting Out Of Service flags

controllers/selfnoderemediation_controller.go
SNR should allow removal of redundant remediations - a remediation of a node that no longer exist since MDR deleted the node and triggered a provisioning of a new one
When SNR detects a remediation that is both deleted and marked as Timeout by NHC it will remove the finilizer
[ECOPROJECT-2489](https://issues.redhat.com//browse/ECOPROJECT-2489)
=> Remove finilizer when deleted SNR is marked with NHC Timeout

controllers/selfnoderemediation_controller.go
SNR should allow removal of redundant remediations - a remediation of a node that no longer exist since MDR deleted the node and triggered a provisioning of a new one.
Currently there is a bug in the code which prevents SNR reaching that logic, this PR fixes it.
When SNR detects a remediation that is both deleted and marked as Timeout by NHC it should remove the finilizer. 
This PR removed an unnecessary check of the CR deletion timestamp that preceded this logic and prevented reaching this logic and the removal of the finilizer.
[ECOPROJECT-2489](https://issues.redhat.com//browse/ECOPROJECT-2489)
=> Fix Deletion timestamp check

controllers/tests/controller/selfnoderemediation_controller_test.go, controllers/tests/controller/suite_test.go, pkg/peers/peers.go, pkg/watchdog/fake.go, pkg/watchdog/synchronized.go, pkg/watchdog/watchdog_suite_test.go, pkg/watchdog/watchdog_test.go
Controller unit tests are broken. They have false positives because they all use the same watchdog.
Also, one unit test is testing for the wrong result.
- fix error handling in peers component
- add unit test for watchdog
- fixed issues in controller unit test
For details see commit messages.
Fixes issues with #238 
There are new and fixed tests
=> Fix watchdog usage in controller unit tests

.gitignore, Makefile, api/v1alpha1/selfnoderemediationconfig_types.go, bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml, config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml, controllers/selfnoderemediationconfig_controller.go, controllers/tests/config/selfnoderemediationconfig_controller_test.go, controllers/tests/config/suite_test.go, controllers/tests/controller/selfnoderemediation_controller_test.go, controllers/tests/controller/suite_test.go, controllers/tests/shared/shared.go, e2e/self_node_remediation_test.go, install/self-node-remediation-deamonset.yaml, pkg/apicheck/check.go, pkg/controlplane/manager.go
Existing code requires there to be at least one other peer worker node before remediation can occur, precluding SNR from remediating on a configuration with 3 control plane nodes + 1 worker node, which is a scenario that we support for bare minimum deployments.
- Add minPeersForRemediation configuration value.  It defaults to 1, which maintains backward compatibility with existing deployments
- Update getWorkerPeersResponse to take into account the new configuration value and not fail when there isn't another peer, and the user has configured the minimum to zero
Fixes #213
=> Configurable minimum worker nodecount

Makefile
Currently SNR Makefile creates a db-based catalog, which was deprecated
This change create a file-based catalog
https://issues.redhat.com/browse/ECOPROJECT-2583
* Create the file-based catalog and push it to my quay.io repository via Makefile
* Create a CatalogSource pointing to the new catalog
* Install SNR via WebUI, verify that everything works
=> Build file based catalog

pkg/peers/peers.go, pkg/peers/peers_test.go
The logic mapping PodIP to Nodes allows the latter to have empty IP assigned, which makes the agent call itself (localhost) in place of an actual peer, and get misleading information.
The logic to assign PodIP to Node is extracted into a dedicated function, to allow unit testing.
Respect the original logic, the function now ensures only valid PodIP are assigned to all Nodes, and logs and returns an error either if the matching PodIP is missing/empty, or if there is no matching Pod available.
NOTE: Even when an error is returned, all valid IPs are also returned, so that SNR can request a peer update quicker than the default interval, and also use as much as valid Nodes it can find.
fix: [RHWA-13](https://issues.redhat.com//browse/RHWA-13)
A specific unittest was added for the new function.
=> Fix: Handle missing PodIP in Node assignment
