OWNERS

Added OWNERS

---

controllers/controller_test.go
controllers/selfnoderemediation_controller.go
e2e/self_node_remediation_test.go
pkg/peerhealth/client_server_test.go
pkg/peerhealth/server.go
pkg/peerhealth/suite_test.go

changing ppr entries to snr.
This is split into 3 commits: 
- Entry changes in logs
- Entry changes in comments & test code naming
- Entry changes in variable and method names

Update ppr to snr

---

bundle/manifests/self-node-remediation.clusterserviceversion.yaml
config/manifests/bases/self-node-remediation.clusterserviceversion.yaml

Updated Search Key word from PP to SNR in order for the operator to appear in OCP UI when searched.

Replace PP with SNR search key word

---

bundle/manifests/self-node-remediation.clusterserviceversion.yaml
config/manifests/bases/self-node-remediation.clusterserviceversion.yaml

- Remove OCP annotation (disconnected)
- Adding description

Update CSV - OCP Annotation & Description

---

api/v1alpha1/selfnoderemediation_types.go
bundle/manifests/self-node-remediation.clusterserviceversion.yaml
bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml
config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediations.yaml
config/manifests/bases/self-node-remediation.clusterserviceversion.yaml
controllers/selfnoderemediation_controller.go
main.go

add LastError field to snr status. add function to update this field in the controller and return the error

capture last error message from reconcile in snr CR status

---

api/v1alpha1/selfnoderemediation_types.go
bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml
bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediations.yaml
config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml

Signed-off-by: Michael Shitrit <mshitrit@redhat.com>

Change default remediation to ResourceDeletion

---

controllers/selfnoderemediation_controller.go

Bug fix https://issues.redhat.com/browse/ECOPROJECT-827

Force delete VA when using resource deletion strategy

---

README.md

Adding new SNR icon to README similar to [NMO](https://github.com/medik8s/node-maintenance-operator/pull/47) and [NHC](https://github.com/medik8s/node-healthcheck-operator/pull/126) PRs.

Add SNR icon in README

---

README.md

SNR is out in [OperatorHub](https://operatorhub.io/operator/self-node-remediation).

Update link to OperatorHub in Readme

---

bundle/manifests/self-node-remediation.clusterserviceversion.yaml
config/manager/kustomization.yaml
config/manifests/bases/self-node-remediation.clusterserviceversion.yaml

Signed-off-by: Michael Shitrit <mshitrit@redhat.com>

Set SNR version to 0.5.0

---

bundle/manifests/self-node-remediation.clusterserviceversion.yaml

updating skipRange in the generated csv which was missed in the original PR.

updating skipRange in generated csv

---

.github/workflows/post-submit.yaml
.github/workflows/pre-submit.yaml
Dockerfile
go.mod

upgrade goland to 1.19 in order to resolve [ECOPROJECT-1023](https://issues.redhat.com//browse/ECOPROJECT-1023)

ECOPROJECT-1023 Bug Fix - Upgrade SNR  Go 1.18 to Go 1.19

---

api/v1alpha1/groupversion_info.go
controllers/selfnoderemediation_controller.go
controllers/selfnoderemediation_controller_test.go
pkg/apicheck/check.go
pkg/controlplane/manager.go
pkg/watchdog/linux.go

Signed-off-by: Michael Shitrit <mshitrit@redhat.com>

minor auto-lint generated changes due to switch to golang 1.19

---

.github/workflows/pre-submit.yaml
Makefile
bundle/manifests/self-node-remediation.clusterserviceversion.yaml
config/manager/kustomization.yaml

Verifying bundle & manifest are updated.

Verify bundle

---

e2e/self_node_remediation_test.go
e2e/utils/pod.go
main.go
pkg/controlplane/manager.go

As part of [ECOPROJECT-1073](https://issues.redhat.com//browse/ECOPROJECT-1073) adding etcd health check as part of control-plane node diagnostics.
Tested on local cluster.

Enable etcd healthcheck

---

pkg/controlplane/manager.go

Control Plane diagnostics runs when there is no API connectivity and the control plane seems to be partially isolated.
Due to the nature of etcd it's health check is almost guaranteed to fail under those conditions, making it redundant.

remove etcd check from cp diagnostics

---

controllers/selfnoderemediation_controller.go
controllers/selfnoderemediation_controller_test.go
controllers/suite_test.go

Now the remediation is stuck when there is no SNR pod on the unhealthy node after it's rebooted.
Because isNodeRebootCapable() always tries to check if the SNR pod is there on the unhealthy node.
If the SNR pod can't restart, resources won't be deleted after rebooting the unhealthy node. This is the issue this PR fixes.

Skip SNR pod check after node is rebooted

---

PROJECT
api/v1alpha1/selfnoderemediation_webhook.go
api/v1alpha1/selfnoderemediation_webhook_test.go
api/v1alpha1/selfnoderemediationtemplate_webhook.go
api/v1alpha1/selfnoderemediationtemplate_webhook_test.go
api/v1alpha1/webhook_suite_test.go
bundle/manifests/self-node-remediation.clusterserviceversion.yaml
config/webhook/manifests.yaml
main.go
pkg/utils/taints.go

This PR
- Adds validation to remediation strategies on SNR (previously only on template) - in order to fix [ECOPROJECT-1232](https://issues.redhat.com//browse/ECOPROJECT-1232)
- Check Major and Minor version (previously Major version was checked instead of minor)  - in order to fix [ECOPROJECT-1233](https://issues.redhat.com//browse/ECOPROJECT-1233)

Bug fixes ECOPROJECT-1232  & ECOPROJECT-1233

---

bundle/manifests/self-node-remediation-ext-remediation_rbac.authorization.k8s.io_v1_clusterrole.yaml
config/rbac/external_remediation_clusterrole.yaml

Allow NHC to watch and update the CR

Update ext remediation rule

---

controllers/selfnoderemediation_controller.go

Signed-off-by: Carlo Lobrano <c.lobrano@gmail.com>

Fix minor typos

---

api/v1alpha1/selfnoderemediation_types.go
controllers/selfnoderemediation_controller.go
controllers/selfnoderemediation_controller_test.go

In order to fix ticket [ECOPROJECT-1246](https://issues.redhat.com//browse/ECOPROJECT-1246) ,and in context of NHC PR: https://github.com/medik8s/node-healthcheck-operator/pull/208
This PR add the support to Succeeded Condition in SNR

Support Succeeded Condition

---

controllers/selfnoderemediationconfig_controller.go

Preventing recreation of config in case it was deleted in order to fix [ECOPROJECT-1277](https://issues.redhat.com//browse/ECOPROJECT-1277)

Do not recreate config if deleted

---

pkg/watchdog/linux.go

Typo fix for Bug [ECOPROJECT-1313](https://issues.redhat.com//browse/ECOPROJECT-1313)

log typo fix

---

Makefile

Similar to [NMO's PR](https://github.com/medik8s/node-maintenance-operator/pull/12), and [NHC's PR](https://github.com/medik8s/node-healthcheck-operator/pull/210).
Add [.PHONY](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html) to each target.

Add .Phony to Makefile

---

main.go
pkg/utils/taints.go
pkg/utils/taints_test.go

Bug fix for [ECOPROJECT-1325](https://issues.redhat.com//browse/ECOPROJECT-1325)

Handle plus sign in minor version

---

api/v1alpha1/selfnoderemediationconfig_types.go
api/v1alpha1/selfnoderemediationconfig_webhook.go
api/v1alpha1/selfnoderemediationconfig_webhook_test.go
api/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
controllers/selfnoderemediationconfig_controller.go
controllers/selfnoderemediationconfig_controller_test.go

This PR meant to solve ECOPROJECT-1235, it would allow the user to use SNR configuration in order to create customized tolerations on SNR's daemonset.

Support custom toleration on ds

---

config/default/manager_auth_proxy_patch.yaml

Not used yet, but just in case...
Fixes HTTP/2 CVE

Update RBAC proxy image and config

---

controllers/selfnoderemediation_controller.go
controllers/tests/controller/selfnoderemediation_controller_test.go
controllers/tests/controller/suite_test.go
pkg/peerhealth/suite_test.go

as part of [ECOPROJECT-1662](https://issues.redhat.com//browse/ECOPROJECT-1662) Adding events for better visibility of SNR remediation process.

Add events

---

pkg/certificates/storage.go
pkg/watchdog/linux.go

- Replace deprecated pointer.BoolPtr with pointer.Bool
- Replace deprecated ioutil.ReadDir with os.ReadDir

Fix some deprecations

---

Makefile

Add `bundle-cleanup` Makefile target to remove a bundle installed via
`bundle-run`

Add Bundle-cleanup

---

bundle/manifests/self-node-remediation.clusterserviceversion.yaml
config/manifests/bases/self-node-remediation.clusterserviceversion.yaml

[ECOPROJECT-1762](https://issues.redhat.com//browse/ECOPROJECT-1762)
Using new ns for SNR

Set new suggested namespace in CSV

---

install/self-node-remediation-deamonset.yaml

[ECOPROJECT-1804](https://issues.redhat.com//browse/ECOPROJECT-1804)
Getting an error while trying to set up softdog (in case watchdog isn't found)

support executing softdog command

---

controllers/selfnoderemediation_controller.go
controllers/tests/controller/selfnoderemediation_controller_test.go

- Addressing [this](https://github.com/medik8s/self-node-remediation/pull/176#discussion_r1458705277) comment regarding wrong assertion
- Addressing [this](https://github.com/medik8s/self-node-remediation/pull/174#discussion_r1457053377) comment, modifying SNR events call to use common pkg
- Fixing another flaky test

Fixing some left overs from other merged PRs

---

.github/workflows/post-submit.yaml

Remove combined NHC / SNR index image because it couples NHC and SNR go versions

Remove combined NHC / SNR index image 

---

controllers/selfnoderemediation_controller.go

[ECOPROJECT-1864](https://issues.redhat.com//browse/ECOPROJECT-1864)
fix bug, last error was shadowed by updateConditions result

Last error not recorded for missing node

---

Makefile

Missing squared brackets around all "if" conditions.

Fix verify-previous-version check

---

Makefile

- Update operator namespace
- Create Namespace if not exist

Create Namespace if it does not exist

---

.github/workflows/release.yml
Makefile

- Install envsubst locally if necessary
- Add target to build RH community bundle with OCP Annotations
- Automate RH community bundle release with Github Action

Automate RH Community bundle creation

---

.ci-operator.yaml
Dockerfile
Makefile
bundle.Dockerfile
bundle/manifests/self-node-remediation.clusterserviceversion.yaml
bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediations.yaml
bundle/manifests/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
bundle/metadata/annotations.yaml
config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediationconfigs.yaml
config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediations.yaml
config/crd/bases/self-node-remediation.medik8s.io_selfnoderemediationtemplates.yaml
go.mod
go.sum

updating versions

---

Dockerfile

update base image to ubi9

---

Makefile

Introduce a new target, `bundle-run-update`, for testing an operator upgrade.
It could be used as well for downgrading or reinstalling the operator (instead of running the _bundle-cleanup_ and then _bundle-run_).
Run 'VERSION=SOME_VERSION' prior to running the bundle-run or bundle-run-update targets to modify the installed or replaced bundle CSV.
The new target will be used for testing operator upgrades in OCP CI (e.g., [NMO and FAR](https://github.com/openshift/release/pull/50559) ).
Similar PR to [NMO #120](https://github.com/medik8s/node-maintenance-operator/pull/120) and [FAR #139](https://github.com/medik8s/fence-agents-remediation/pull/139).
* Add `bundle-run-update` target
* Change var name `BUNDLE_RUN_NAMESPACE` to `OPERATOR_NAMESPACE` in Makefile …

Update bundle image

---

.github/workflows/post-submit.yaml
.github/workflows/release.yml
Makefile
bundle/manifests/self-node-remediation.clusterserviceversion.yaml
config/manifests/bases/self-node-remediation.clusterserviceversion.yaml

OKD community pipeline is verifying the presence of OCP annotation.
- Add OCP annotation to OKD bundle
Moreover I took this chance to add the following improvements
- Add .spec.replaces field to OKD bundle only (K8S community doesn't want it)
- Use clearer names for Makefile targets
- Fix go-install-tool error message

Add OCP annotation to OKD bundle

---

README.md

- improve Readme
- test tide
Improved wording for NHC

Small improvement in Readme

---

bundle/manifests/self-node-remediation.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml

Reduce logging level

---

controllers/selfnoderemediation_controller.go

This PR is followup PR to #249 , we've realized that when SNR Cr is deleted a cleanup of the node taints is needed, otherwise we recovery isn't complete.
When a Timeout CR is deleted, In case a node exist in addition to removing the finalizer from the CR remove the "NoExecute" taints placed on the node.
[ECOPROJECT-2489](https://issues.redhat.com//browse/ECOPROJECT-2489)

Clean taints from a timeout deleted node
